include classpath("application.conf")

node-address {
  protocol = http
  host = "elasticmq"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

generate-node-address = false

queues {
  thermal-print-queue {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait = 0 seconds
  }
  thermal-response-queue {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait = 0 seconds
  }
}

aws {
  region = us-east-1
  accountId = "000000000000"
}
